name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.0
  google_sign_in: ^6.0.0
  intl: ^0.18.0
  google_fonts: 4.0.3
  flutter_screenutil: 5.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

